package com.andremw96.qocrkmm.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ImageBitmap
import kotlinx.coroutines.delay

@Composable
fun CameraScreenComposable(
    onTextGenerated: (String, ImageBitmap) -> Unit,
) {
    var showCamera by remember { mutableStateOf(false) }
    var textGenerated by remember { mutableStateOf<Pair<String?, ImageBitmap?>>(Pair(null, null)) }
    LaunchedEffect(Unit) {
        if (!showCamera) {
            delay(300) // for animation
            showCamera = true
        }
    }
    Box(Modifier.fillMaxSize().background(Color.Black)) {
        if (showCamera) {
            CameraView(Modifier.fillMaxSize(), onTextGenerated = { text, imageBitmap ->
                println("generated text $text")
                textGenerated = Pair(text, imageBitmap)
            })
        }

        if (textGenerated.first != null && textGenerated.second != null) {
            onTextGenerated(
                textGenerated.first!!,
                textGenerated.second!!
            )
        }
    }
}
